### ISSUE TITLE
evQueue extension broken by Firefox' https-only mode

### ISSUE THREAD

**Issue by njean42** [coldsource/evqueue-core#9]
Just noticed that the _https-only mode_ in Firefox breaks the evQueue frontend (tested the extension, probably true of the react frontend as well).

![image](https://user-images.githubusercontent.com/11575528/170042425-788bafa2-190e-475d-865f-bebf81b36a1e.png)

![image](https://user-images.githubusercontent.com/11575528/170042516-13f93ad5-f715-44fa-86d0-36319d71a9e3.png)

![image](https://user-images.githubusercontent.com/11575528/170042578-586e001d-db05-493a-aec5-01886ac6139a.png)

I couldn't get the `ws://1.2.3.4:5001` URL into the allowlist of exceptions for the _http-only mode_ ("_Manage exceptions_").

Not sure if there's anything that can be done in evQueue to accommodate for this mode, or if it's a Firefox bug.
I used to use the EFF's _https everywhere_ addon, which they're now deprecating and advising to switch to browsers own modes (did not cause this issue though :slightly_smiling_face:).

**Comment by coldsource** [comment]
SSL support has been added on "logs" branch.

You must compile against libwebsockets >= 3.0

You can enable it by setting ws.ssl.crt and ws.ssl.key in your configuration file.

If you are using self signed certificate, first go to https://localhost:5001 (or whatever you have configured) and accept security breach of self signed certificate.

Use wss:// instead of ws:// in your front (or plugin) configuration.

And you are done.

**Comment by njean42** [comment]
Works perfectly, also with an actual certificate (thanks Let's Encrypt)
Goes along well with Firefox's https-only mode!
